#!/bin/bash
# NotaryFlow setup — run this once to wire Supabase and start the app.
# Usage: bash setup.sh

set -e

export PATH="/opt/homebrew/bin:$PATH"

BOLD="\033[1m"
GREEN="\033[32m"
YELLOW="\033[33m"
CYAN="\033[36m"
RESET="\033[0m"

PROJECT_DIR="/Users/damienlugo/Developer/notaryflow"
cd "$PROJECT_DIR"

echo ""
echo -e "${BOLD}NotaryFlow Setup${RESET}"
echo "────────────────────────────────────────"
echo ""

# ── Step 1: Check Node ────────────────────────────────────────────────────────
if ! command -v node &>/dev/null; then
  echo "Node.js is not installed. Install it from https://nodejs.org then run this script again."
  exit 1
fi

# ── Step 2: Install npm deps if needed ───────────────────────────────────────
if [ ! -d "node_modules" ]; then
  echo -e "${CYAN}Installing npm packages...${RESET}"
  npm install --silent
fi

# ── Step 3: Check if already configured ──────────────────────────────────────
if [ -f ".env.local" ]; then
  source .env.local 2>/dev/null || true
  if [ -n "$NEXT_PUBLIC_SUPABASE_URL" ]; then
    echo -e "${GREEN}✓ .env.local already exists and has Supabase keys.${RESET}"
    echo ""
    echo "Skipping key setup. Delete .env.local to reconfigure."
    echo ""
    SKIP_KEYS=true
  fi
fi

# ── Step 4: Walk through Supabase setup ──────────────────────────────────────
if [ -z "$SKIP_KEYS" ]; then

  echo -e "${BOLD}You need a free Supabase project.${RESET}"
  echo ""
  echo -e "  1. Open ${CYAN}https://supabase.com${RESET} and sign in (or create a free account)."
  echo "  2. Click  New project."
  echo "     • Name: notaryflow"
  echo "     • Generate a password and SAVE IT somewhere."
  echo "     • Region: closest to you."
  echo "     • Plan: Free."
  echo "  3. Wait ~2 minutes for it to finish provisioning."
  echo "  4. Click the gear icon (Settings) → API."
  echo ""
  echo "Press Enter here once your project is ready and you can see the API page..."
  read -r

  echo ""
  echo -e "${BOLD}Paste your values one at a time. Press Enter after each.${RESET}"
  echo "(They look like long strings of letters and numbers.)"
  echo ""

  echo -e -n "${CYAN}Project URL${RESET} (looks like https://xxxxx.supabase.co): "
  read -r SUPABASE_URL
  SUPABASE_URL="${SUPABASE_URL%/}"   # strip trailing slash if present

  echo -e -n "${CYAN}Publishable key${RESET} (starts with sb_publishable_ — click the copy icon next to it): "
  read -r SUPABASE_ANON_KEY

  echo -e -n "${CYAN}Secret key${RESET} (scroll down to Secret keys, click the copy icon): "
  read -r SUPABASE_SERVICE_KEY

  echo ""
  echo -e "${CYAN}Writing .env.local...${RESET}"

  cat > .env.local <<ENVFILE
# Generated by setup.sh

NEXT_PUBLIC_APP_URL=http://localhost:3000

NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_KEY}

# Stripe — leave blank until billing session
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
STRIPE_PRICE_SOLO=
STRIPE_PRICE_PRO=

# Resend — optional
RESEND_API_KEY=
ENVFILE

  echo -e "${GREEN}✓ .env.local saved.${RESET}"

  # ── Step 5: Extract project ref and open SQL editor ───────────────────────
  # URL format: https://abcdefgh.supabase.co
  PROJECT_REF=$(echo "$SUPABASE_URL" | sed 's|https://||' | cut -d'.' -f1)
  SQL_EDITOR_URL="https://supabase.com/dashboard/project/${PROJECT_REF}/sql/new"

  echo ""
  echo -e "${BOLD}Now run the two database migration files in Supabase.${RESET}"
  echo ""
  echo "  1. Opening your Supabase SQL Editor in the browser..."
  open "$SQL_EDITOR_URL" 2>/dev/null || echo "  → Go to: $SQL_EDITOR_URL"
  echo ""
  echo "  2. Opening the first migration file..."
  open -e "${PROJECT_DIR}/lib/db/migrations/0001_init.sql" 2>/dev/null \
    || open "${PROJECT_DIR}/lib/db/migrations/0001_init.sql" 2>/dev/null \
    || echo "     File: ${PROJECT_DIR}/lib/db/migrations/0001_init.sql"
  echo ""
  echo "     • Select ALL the text in that file (Cmd+A), copy it (Cmd+C)."
  echo "     • Switch to your browser, paste into the SQL Editor (Cmd+V)."
  echo "     • Click the green RUN button (bottom right)."
  echo "     • You should see: Success. No rows returned."
  echo ""
  echo "Press Enter when the first migration is done..."
  read -r

  echo ""
  echo "  3. Opening the second migration file..."
  open -e "${PROJECT_DIR}/lib/db/migrations/0002_features.sql" 2>/dev/null \
    || open "${PROJECT_DIR}/lib/db/migrations/0002_features.sql" 2>/dev/null \
    || echo "     File: ${PROJECT_DIR}/lib/db/migrations/0002_features.sql"
  echo ""
  echo "     • Select ALL, copy, paste into Supabase SQL Editor, click RUN."
  echo "     • You should see: Success. No rows returned."
  echo ""
  echo "Press Enter when the second migration is done..."
  read -r

  # ── Step 6: Set Auth redirect URL ────────────────────────────────────────
  AUTH_URL="https://supabase.com/dashboard/project/${PROJECT_REF}/auth/url-configuration"
  echo ""
  echo "  4. One more thing — tell Supabase your app's address."
  echo "     Opening Auth settings..."
  open "$AUTH_URL" 2>/dev/null || echo "  → Go to: $AUTH_URL"
  echo ""
  echo "     • Set  Site URL  to:  http://localhost:3000"
  echo "     • Under  Redirect URLs  click Add URL and enter:"
  echo "       http://localhost:3000/auth/callback"
  echo "     • Click Save."
  echo ""
  echo "Press Enter when done..."
  read -r

fi

# ── Step 7: Kill any existing dev server and start fresh ─────────────────────
echo ""
echo -e "${CYAN}Starting the app...${RESET}"

# Kill any process on port 3000
if lsof -ti:3000 &>/dev/null; then
  echo "Stopping existing server on port 3000..."
  lsof -ti:3000 | xargs kill -9 2>/dev/null || true
  sleep 1
fi

echo ""
echo -e "${GREEN}${BOLD}All done! Opening the app now.${RESET}"
echo ""
echo -e "The app is at: ${CYAN}http://localhost:3000${RESET}"
echo "Sign up at:    http://localhost:3000/sign-up"
echo ""
echo "(This window runs the server. To stop it press Ctrl+C.)"
echo ""

# Open the browser after a short delay
(sleep 3 && open "http://localhost:3000/sign-up") &

npm run dev
